#!/usr/bin/env python3
"""
Converts a bump configuration file to the form required by bump version 2.
"""

from inform import fatal, os_error
from pathlib import Path
import nestedtext as nt

OLD_CFG_FILE = '.bump.cfg'
NEW_CFG_FILE = '.bump.cfg.nt'

try:
    code = Path(OLD_CFG_FILE).read_text()
    compiled = compile(code, OLD_CFG_FILE, 'exec')
    old_cfg = {}
    exec(compiled, old_cfg)

    new_cfg = dict(
        major = old_cfg['major'],
        minor = old_cfg['minor'],
        patch = old_cfg['patch'],
        iteration = "0",
        type = "release",
        files = {}
    )
    files = new_cfg['files']
    for each in old_cfg.get('version', []):
        path, version = each.split()
        if path not in files:
            files[path] = {}
        files[path]['version'] = version
    for each in old_cfg.get('date', []):
        path, date = each.split()
        if path not in files:
            files[path] = {}
        files[path]['date'] = date

    nt.dump(new_cfg, NEW_CFG_FILE)
except OSError as e:
    fatal(os_error(e))
except nt.NestedTextError as e:
    e.report()
