#!/usr/bin/env bash

set nonomatch

# the rest is common to all python directories
rm -f *.pyc *.pyo .test*.sum expected result install.out
rm -rf build *.egg-info dist __pycache__ .coverage .coverage-html htmlcov .eggs .tox
for i in */clean
do
    if [[ "$i" == '*/clean' ]]
    then
        break
    fi
    ( cd ${i%/*}; ./clean )
done
